language: node_js
node_js:
  - "11.4.0"
after_success: npm run coverage
deploy:
  provider: npm
  email: "bronley@gmail.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true